### ISSUE TITLE
prompt can changed?

### ISSUE THREAD

**Issue by iampere4u** [Sander2222/sa_ffa#2]
prompt can changed to qb-target I am unable to find what is the event for opening ffa ui I used this FFAUISearch()but it didnnt worked can u help with this?

**Comment by Sander2222** [comment]
Hey did you tried this with export:
`    exports['sa_ffa']:FFAUISearch()`

and did you called this clientside and maybe you get a clientside error?

**Comment by iampere4u** [comment]
I already called this but didnt worked like can u give example of qb/ox target with this export?

**Comment by Sander2222** [comment]
So i never used ox target, but you can look at thoose examples from ox himself:

https://github.com/overextended/ox_target/blob/main/client/defaults.lua

**Comment by iampere4u** [comment]
can u like create ffa join command? because targets are not recognising exports
